name: mlflow-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12.7
  - pip
  - mlflow=2.19.0
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - numpy=2.1.3
  - scipy=1.15.3
  - pip:
    - pyarrow
