name: ML Project CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Check Python environment
        run: python --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Run MLflow project (train & log model)
        run: |
          python MLProject/modelling.py --data_path MLProject/personality.csv --n_estimators 100 --max_depth 10

      - name: Get latest MLflow run ID
        id: get_run
        run: |
          run_id=$(ls -td mlruns/0/* | head -1 | xargs -n1 basename)
          echo "RUN_ID=$run_id" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/personality-model:latest .

      - name: Login to DockerHub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Tag Docker Image
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/personality-model:latest ${{ secrets.DOCKER_USERNAME }}/personality-model:latest

      - name: Push Docker Image to DockerHub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/personality-model:latest
