name: MLflow Docker Pipeline

on:
  push:
    branches: [ main ]

jobs:
  mlflow-docker:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    - name: Install dependencies
      run: |
        pip install mlflow==2.19.0 docker

    - name: Run MLflow with Docker
      run: |
        cd MLProject
        mlflow run . --env-manager=docker

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push model image
      run: |
        cd MLProject
        RUN_ID=$(mlflow runs list --experiment-id 0 -n 1 | awk 'NR==2 {print $4}')
        
        # Build Docker image dari model MLflow
        mlflow models build-docker -m "mlruns/0/$RUN_ID/artifacts/model" -n "personality-model"
        
        # Tag dan push
        docker tag personality-model ${{ secrets.DOCKER_HUB_USERNAME }}/personality-model:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/personality-model:latest
