name: MLflow CI/CD Pipeline (Advance)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlflow-pipeline:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      # ---- 1. Setup Conda Environment ----
      - uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.12.7"
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env

      # ---- 2. Run MLflow Training ----
      - name: Train model
        run: |
          conda activate mlflow-env
          cd MLProject
          mlflow run . --env-manager=local

      # ---- 3. Handle Artifacts ----
      - name: Get run ID
        id: get_run_id
        run: |
          RUN_ID=$(mlflow runs list --experiment-id 0 -n 1 | awk 'NR==2 {print $4}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV

      - name: Prepare artifacts
        run: |
          mkdir -p artifacts
          cp -r mlruns/0/${{ env.RUN_ID }}/artifacts/model artifacts/
          cp mlruns/0/${{ env.RUN_ID }}/meta.yaml artifacts/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mlflow-artifacts
          path: artifacts
          retention-days: 1

      # ---- 4. Docker Operations ----
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" -n "personality-classifier"
          docker tag personality-classifier ghcr.io/${{ github.repository_owner }}/personality-classifier:latest
          docker push ghcr.io/${{ github.repository_owner }}/personality-classifier:latest
