name: MLflow CI/CD Pipeline (Advance)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlflow-pipeline:
    runs-on: ubuntu-latest
    permissions:
      packages: write  # Required for GHCR
      contents: write  # Required for artifacts

    steps:
      # ---- Setup Environment ----
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          pip install -r MLProject/conda.yaml
          pip install mlflow==2.19.0

      # ---- Run MLflow Training ----
      - name: Train model with MLflow
        run: |
          cd MLProject
          mlflow run . --env-manager=local

      # ---- Capture Run ID for Artifacts ----
      - name: Get latest run ID
        id: get_run_id
        run: |
          RUN_ID=$(mlflow runs list --experiment-id 0 -n 1 | awk 'NR==2 {print $4}')
          echo "RUN_ID=$RUN_ID" >> $GITHUB_ENV
          echo "::set-output name=run_id::$RUN_ID"

      # ---- Package and Upload Model Artifacts ----
      - name: Prepare model artifacts
        run: |
          mkdir -p model_artifacts
          cp -r mlruns/0/${{ env.RUN_ID }}/artifacts/model model_artifacts/
          cp mlruns/0/${{ env.RUN_ID }}/meta.yaml model_artifacts/

      - name: Upload model artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: model_artifacts

      # ---- Build & Push Docker Image to GHCR ----
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build MLflow Docker Image
        run: |
          mlflow models build-docker -m "mlruns/0/${{ env.RUN_ID }}/artifacts/model" -n "personality-classifier"

      - name: Tag and Push to GHCR
        run: |
          docker tag personality-classifier ghcr.io/${{ github.repository_owner }}/personality-classifier:latest
          docker push ghcr.io/${{ github.repository_owner }}/personality-classifier:latest
