name: ML Project CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt
          pip install mlflow

      - name: Prepare MLflow tracking
        run: |
          mkdir -p MLProject/mlruns
          chmod 777 -R MLProject/mlruns

      - name: Train and log model with MLflow
        run: |
          cd MLProject
          python modelling.py \
            --data_path personality.csv \
            --n_estimators 100 \
            --max_depth 10

      - name: Get latest MLflow run ID
        id: get_run_id
        run: |
          cd MLProject
          RUN_ID=$(mlflow runs list --experiment-id 0 -n 1 | awk 'NR==2 {print $4}')
          echo "run_id=$RUN_ID" >> $GITHUB_OUTPUT
          echo "MODEL_PATH=mlruns/0/$RUN_ID/artifacts/model" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image from MLflow Model
        run: |
          cd MLProject
          mlflow models build-docker \
            -m "${{ env.MODEL_PATH }}" \
            -n "personality-classification"

      - name: Tag and Push Docker Image
        run: |
          docker tag personality-classification ${{ secrets.DOCKER_USERNAME }}/personality-classification:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/personality-classification:latest
