name: MLflow Pipeline with Pip

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  mlflow-pipeline:
    runs-on: ubuntu-latest
    env:
      MLFLOW_TRACKING_URI: file://${{ github.workspace }}/mlruns

    steps:
    # --- 1. Setup Awal ---
    - name: Checkout repository
      uses: actions/checkout@v4

    # --- 2. Setup Python ---
    - name: Set up Python 3.12.7
      uses: actions/setup-python@v5
      with:
        python-version: "3.12.7"

    # --- 3. Install Dependencies ---
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r MLProject/requirements.txt

    # --- 4. Run MLflow Project ---
    - name: Run training
      run: |
        cd MLProject
        mlflow run . --env-manager=local

    # --- 5. Docker Operations ---
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        cd MLProject
        RUN_ID=$(mlflow runs list -n 1 | awk 'NR==2 {print $4}')
        mlflow models build-docker -m "mlruns/0/$RUN_ID/artifacts/model" -n "mlflow-pip-model"
        docker tag mlflow-pip-model ${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-pip-model:latest
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/mlflow-pip-model:latest
