name: ML Project CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r MLProject/requirements.txt

      - name: Train and log model with MLflow
        run: |
          python MLProject/modelling.py \
            --data_path MLProject/personality.csv \
            --n_estimators 100 \
            --max_depth 10

      - name: Get latest MLflow model path
        id: get_model_path
        run: |
          MODEL_PATH=$(find mlruns -type d -path "*/model" | sort -r | head -n 1)
          echo "model_path=$MODEL_PATH" >> $GITHUB_OUTPUT

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image from MLflow Model
        run: |
          echo "Building Docker image from: ${{ steps.get_model_path.outputs.model_path }}"
          mlflow models build-docker \
              -m "${{ steps.get_model_path.outputs.model_path }}" \
              -n personality-classification

      - name: Tag Docker Image
        run: docker tag personality-classification ${{ secrets.DOCKER_USERNAME }}/personality-classification:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/personality-classification:latest
